version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Containerfile
    container_name: PchClk
    ports:
      - "3000:3000"
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - data:/app/data
    restart: always

volumes:
  data:
    driver: local