version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Containerfile
    container_name: pchclk_backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - pchclk_db_data:/app/data
    restart: always

volumes:
  pchclk_db_data:
    driver: local
